repository_name: "Leansso"
SECRET_KEY_BASE: ""
HTTP_AUTHORIZATION: 'Authorization'
SERVER_URL: 'http://localhost:3000'
DATABASE_NAME: 'leansso_production'
DATABASE_USERNAME: ''
DATABASE_PASSWORD: ''
RAILS_SERVE_STATIC_FILES: 'true'